# Generated by Django 3.1.6 on 2021-02-10 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_auto_20210209_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='url',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
